import ThemeProviders from './theme-provider';
import AuthProvider from './auth-provider';
import '../styles/globals.scss';
import { Titillium_Web, Roboto_Mono } from 'next/font/google';

const inter = Titillium_Web({
  weight: ['400', '600'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

const mono = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-noto-mono',
});

export const metadata = {
  title: 'Tickets',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html suppressHydrationWarning lang="en" className={`${inter.variable} ${mono.variable}`}>
      <body>
        <ThemeProviders>
          <AuthProvider>{children}</AuthProvider>
        </ThemeProviders>
      </body>
    </html>
  );
}
